export default ProductList = [
    {
      id: 1,
      size:'2.5m',
      Title: "Hijab Kingry Pashmina Shawl",
      Gender:'Women',
      ProductType: "Shawl",
      Fabric:'Pashmina',
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      ProductCode: "HJ-001",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      SubDescription: "Hand made Indian Wool Shawl",
      Description: "Best for Hijab with a luxurious Hand made border.",
      PurchasePrice: 1200,
      WholeSalePrice: 1500,
      Season:'Winter',
      RetailPrice: 3000,
      Category: "Shawl",
      Stuff: "Loan",
      onSale: true,
      SalePercentage: 30,
      createAt: "2021-09-01",
      Stock: 100,
      Popular: true,
      Trending: true,
      Rating: 5,
      Reviews: [
        { id: 1, Review: "Good Product", Rating: 5, Name: "Ali Ashfaq" },
        { id: 2, Review: "Good Quality", Rating: 5, Name: "Ali Raza" }
      ],
      Likes: 100,
      LikedBy: [{ id: 1, Name: "Ali Ashfaq" }, { id: 2, Name: "Ali Raza" }],
      updateAt: "2024-09-01"
    },
    {
      id: 2,
      size:'2.5m',

      ProductType: "Shawl",
      Fabric:'Pashmina',
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      Title: "Summer Shawls Embroidered Loan Dupatta",
      Gender:'Women',
      ProductCode: "HJ-002",
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      Description: "Elegant loan dupatta with fine embroidery.",
      SubDescription: "Hand made Indian Wool Shawl",

      PurchasePrice: 900,
      Season:'Summer',

      WholeSalePrice: 1100,
      RetailPrice: 2500,
      Category: "Dupatta",
      Stuff: "Loan",
      onSale: false,
      SalePercentage: 0,
      createAt: "2022-01-01",
      Stock: 150,
      Popular: true,
      size:'2.5m',
      Trending: false,
      Rating: 4.5,
      Reviews: [
        { id: 1, Review: "Beautiful piece", Rating: 4, Name: "Hina Tariq" },
        { id: 2, Review: "Good for daily wear", Rating: 4, Name: "Sara Khan" }
      ],
      Likes: 80,
      LikedBy: [{ id: 1, Name: "Hina Tariq" }, { id: 2, Name: "Sara Khan" }],
      updateAt: "2024-11-11"
    },
    {
      id: 3,
      size:'2.5m',

      ProductType: "Shawl",
      Fabric:'Pashmina',
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      Title: "Woollen Stoller",
      Gender:'Women',
      ProductCode: "HJ-003",
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      Description: "Cozy woollen stoller perfect for winter wear.",
      SubDescription: "Hand made Indian Wool Shawl",
      Season:'Winter',

      PurchasePrice: 800,
      WholeSalePrice: 1000,
      RetailPrice: 2000,
      Category: "Stoller",
      Stuff: "Shafoon",
      onSale: true,
      SalePercentage: 20,
      createAt: "2024-12-01",
      Stock: 120,
      Popular: false,
      Trending: true,
      Rating: 4.7,
      Reviews: [
        { id: 1, Review: "Very warm and soft", Rating: 5, Name: "Ahmed Ali" },
        { id: 2, Review: "Nice quality", Rating: 4, Name: "Zara Yousuf" }
      ],
      Likes: 90,
      LikedBy: [{ id: 1, Name: "Ahmed Ali" }, { id: 2, Name: "Zara Yousuf" }],
      updateAt: "2024-05-15"
    },
    {
      size:'2.5m',

      id: 4,
      ProductType: "Shawl",
      Fabric:'Pashmina',
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      Title: "Velvet Shawl with Embroidery",
      Gender:'Women',
      ProductCode: "HJ-004",
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      Description: "Swiss loan shawl with formal embroidery.",
      SubDescription: "Hand made Indian Wool Shawl",
      Season:'Summer',
      PurchasePrice: 1300,
      WholeSalePrice: 1600,
      RetailPrice: 3500,
      Category: "Shawl",
      Stuff: "Swiss Loan",
      onSale: false,
      SalePercentage: 0,
      createAt: "2024-09-01",
      Stock: 90,
      Popular: true,
      Trending: false,
      Rating: 4.9,
      Reviews: [
        { id: 1, Review: "Perfect for formal events", Rating: 5, Name: "Zainab Noor" },
        { id: 2, Review: "Excellent fabric", Rating: 5, Name: "Farhan Qadir" }
      ],
      Likes: 110,
      LikedBy: [{ id: 1, Name: "Zainab Noor" }, { id: 2, Name: "Farhan Qadir" }],
      updateAt: "2024-04-20"
    },
    {
      size:'2.5m',

      id: 5,
      ProductType: "Shawl",
      Fabric:'Pashmina',
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      Title: "Karalic Border Shawl",
      Gender:'Men',
      ProductCode: "HJ-005",
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      Description: "Karalic border shawl for elegant looks.",
      SubDescription: "Hand made Indian Wool Shawl",
      Season:'Summer',
      PurchasePrice: 1100,
      WholeSalePrice: 1400,
      RetailPrice: 2800,
      Category: "Shawl",
      Stuff: "Karalic",
      onSale: true,
      SalePercentage: 25,
      createAt: "2024-05-01",
      Stock: 80,
      Popular: false,
      Trending: true,
      Rating: 4.8,
      Reviews: [
        { id: 1, Review: "Stylish and beautiful with stunning beautiful design with awesome thread work", Rating: 5, Name: "Fatima Zahra" },
        { id: 2, Review: "I love the border", Rating: 4, Name: "Imran Sheikh" },
        { id: 3, Review: "I love the border design stunning", Rating: 5, Name: "Imran Ali" }

      ],
      Likes: 85,
      LikedBy: [{ id: 1, Name: "Fatima Zahra" }, { id: 2, Name: "Imran Sheikh" }],
      updateAt: "2022-05-10"
    },
    {
      size:'2.5m',

      id: 6,
      ProductType: "Shawl",
      Fabric:'Pashmina',
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      Title: "Embroidered Net Burka",
      Gender:'Men',
      ProductCode: "HJ-006",
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      Description: "Net Burka with detailed embroidery.",
      SubDescription: "Hand made Indian Wool Shawl",
      Season:'Summer',
      PurchasePrice: 1800,
      WholeSalePrice: 2000,
      RetailPrice: 4000,
      Category: "Burka",
      Stuff: "Net",
      onSale: false,
      SalePercentage: 0,
      createAt: "2024-06-01",
      Stock: 70,
      Popular: true,
      Trending: true,
      Rating: 5,
      Reviews: [
        { id: 1, Review: "Very elegant", Rating: 5, Name: "Ayesha Khan" },
        { id: 2, Review: "Love the design", Rating: 5, Name: "Sana Malik" }
      ],
      Likes: 95,
      LikedBy: [{ id: 1, Name: "Ayesha Khan" }, { id: 2, Name: "Sana Malik" }],
      updateAt: "2024-06-15"
    },
    {
      size:'2.5m',

      id: 7,
      ProductType: "Shawl",
      Fabric:'Pashmina',
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      Title: "Barosha Dupatta",
      Gender:'Men',
      ProductCode: "HJ-007",
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      Description: "Soft Barosha dupatta with a sleek look.",
      SubDescription: "Hand made Indian Wool Shawl",
      Season:'Summer',

      PurchasePrice: 1000,
      WholeSalePrice: 1200,
      RetailPrice: 2600,
      Category: "Dupatta",
      Stuff: "Barosha",
      onSale: true,
      SalePercentage: 15,
      createAt: "2024-07-01",
      Stock: 100,
      Popular: false,
      Trending: false,
      Rating: 4.6,
      Reviews: [
        { id: 1, Review: "Nice for casual wear", Rating: 4, Name: "Maha Tariq" },
        { id: 2, Review: "Soft fabric", Rating: 4, Name: "Saba Noor" }
      ],
      Likes: 70,
      LikedBy: [{ id: 1, Name: "Maha Tariq" }, { id: 2, Name: "Saba Noor" }],
      updateAt: "2024-07-20"
    },
    {
      size:'2.5m',

      id: 8,
      ProductType: "Shawl",
      Fabric:'Pashmina',
      Color:[
        { id: 1, Color: "Black" ,Code:'#000000'},
        { id: 2, Color: "Maroon" ,Code:'#800000' },
        { id: 3, Color: "NavyBlue",Code:'#000435' },
        { id: 4, Color: "Beige" ,Code:'#ecdd9a' },
        { id: 5, Color: "Biscotti" ,Code:'#e3c565' },
        { id: 6, Color: "Shortbread" ,Code:'#fbe790' },
      ],
      Gender:'Men',
      ProductCode: "HJ-008",
      Details1: "Hand made Indian Wool Shawl",
      Details2: "Best for Hijab with a luxurious Hand made border.",
      Title: "Embroidered Loan Dupatta",
      Images: [
        { id: 1, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 2, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" },
        { id: 3, Image: "https://res.cloudinary.com/dzv2a0f0i/image/upload/v1726588239/Shawls/avuthkdtiitkokyzzf8p.png" }
      ],
      Description: "Elegant loan dupatta with fine embroidery.",
      SubDescription: "Hand made Indian Wool Shawl",
      PurchasePrice: 900,
      Season:'Summer',
      WholeSalePrice: 1100,
      RetailPrice: 2500,
      Category: "Dupatta",
      Stuff: "Loan",
      onSale: true,
      SalePercentage: 10,
      createAt: "2024-01-01",
      Stock: 150,
      Popular: true,
      Trending: false,
      Rating: 4.5,
      Reviews: [
        { id: 1, Review: "Beautiful piece", Rating: 4, Name: "Hina Tariq" },
        { id: 2, Review: "Good for daily wear", Rating: 4, Name: "Sara Khan" }
      ],
      Likes: 80,
      LikedBy: [{ id: 1, Name: "Hina Tariq" }, { id: 2, Name: "Sara Khan" }],
      updateAt: "2024-02-01"
    },
   
  ];
  